apiVersion: v1
kind: Pod
metadata:
  name: init-testing
spec:
  containers:
  - name: nginx-cont
    image: nginx
    ports:
    - containerPort: 80
  initContainers:
  - name: busybox-init
    image: busybox
    command: ['sh', '-c', 'echo pre-tasks are completed']
