apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-container
        image: nginx
        volumeMounts:
        - name: nfs-volume
          mountPath: 
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
