apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developers-clusterrole
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developers-clusterrolebinding
subjects:
- kind: User
  name: "dev-1"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: developers-clusterrole
  apiGroup: rbac.authorization.k8s.io
