apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-cont
    image: nginx:latest
  tolerations:
  - key: "node"
    operator: "Equal"
    value: "dev"
    effect: "NoSchedule"
