apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-set
spec:
  selector:
    matchLabels:
      app: web-logs
  template:
    metadata:
      labels:
        app: web-logs
    spec:
      containers:
      - name: webserver
        image: nginx:latest
